apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-dekoratoren-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-dekoratoren-api
  minReplicas: {{ min-replicas }}
  maxReplicas: {{ max-replicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ average-utilization }}