apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-dekoratoren-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /person/nav-dekoratoren-api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /person/nav-dekoratoren-api/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /person/nav-dekoratoren-api/internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - namespace: min-side
          application: tms-varselbjelle-api
      external:
        - host: {{ pdl-api-host }}
  envFrom:
    - secret: nav-dekoratoren-api-secret
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 300m
      memory: 384Mi
  azure:
    application:
      enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
