name: Deploy to dev
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build and deploy dev
        uses: ./.github/actions/build-and-deploy
        with:
          ENVIRONMENT: dev

      - name: Deploy HPA
        uses: nais/deploy/actions/deploy@v2
        timeout-minutes: 1
        continue-on-error: true
        env:
          CLUSTER: dev-gcp
          RESOURCE: ./nais/hpa.yaml
          VARS: ./nais/dev-gcp/personbruker.json